var a = 10;
var b = 5;
console.log("a is equal to b", a == b);
console.log("a is not equal to b", a != b);
console.log("a is equal to b", a === b);
console.log("a is not equal to b", a !== b);
console.log("a > b", a > b);
console.log("a < b", a < b);
console.log("a >= b", a >= b);
console.log("a <= b", a <= b);
